Repository All-eatery/EatsFinder-BE, pull requests merged in 2024-06, with the labels that each got.

#2 Feat/entity k
  src/main/kotlin/com/eatsfinder/EatsFinderApplication.kt
  src/main/kotlin/com/eatsfinder/domain/category/model/Category.kt
  src/main/kotlin/com/eatsfinder/domain/comment/model/Comment.kt
  src/main/kotlin/com/eatsfinder/domain/email/model/Email.kt
  src/main/kotlin/com/eatsfinder/domain/follow/model/Follow.kt
  src/main/kotlin/com/eatsfinder/domain/like/model/LikesByPost.kt
  src/main/kotlin/com/eatsfinder/domain/post/model/Post.kt
  src/main/kotlin/com/eatsfinder/domain/starRating/model/StarRating.kt
  src/main/kotlin/com/eatsfinder/domain/user/model/SocialType.kt
  src/main/kotlin/com/eatsfinder/domain/user/model/User.kt
  src/main/kotlin/com/eatsfinder/domain/user/model/UserRole.kt
  src/main/kotlin/com/eatsfinder/domain/user/model/UserStatus.kt
  src/main/kotlin/com/eatsfinder/global/entity/BaseTimeEntity.kt
Labels: ✨ Feat

#4 Feat/swagger k
  build.gradle.kts
  src/main/kotlin/com/eatsfinder/global/swagger/SwaggerConfig.kt
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: ✨ Feat

#6 Feat/oauth k
  build.gradle.kts
  src/main/kotlin/com/eatsfinder/EatsFinderApplication.kt
  src/main/kotlin/com/eatsfinder/domain/user/controller/OAuth2LoginController.kt
  src/main/kotlin/com/eatsfinder/domain/user/dto/OAuth2UserInfo.kt
  src/main/kotlin/com/eatsfinder/domain/user/model/User.kt
  src/main/kotlin/com/eatsfinder/domain/user/repository/UserRepository.kt
  src/main/kotlin/com/eatsfinder/domain/user/service/OAuth2LoginService.kt
  src/main/kotlin/com/eatsfinder/domain/user/service/OAuthUserService.kt
  src/main/kotlin/com/eatsfinder/global/entity/BaseTimeEntity.kt
  src/main/kotlin/com/eatsfinder/global/oauth/client/OAuth2Client.kt
  src/main/kotlin/com/eatsfinder/global/oauth/client/OAuth2ClientService.kt
  src/main/kotlin/com/eatsfinder/global/oauth/client/google/GoogleOAuth2Client.kt
  src/main/kotlin/com/eatsfinder/global/oauth/client/google/dto/GoogleTokenResponse.kt
  src/main/kotlin/com/eatsfinder/global/oauth/client/google/dto/GoogleUserInfoResponse.kt
  src/main/kotlin/com/eatsfinder/global/oauth/client/kakao/KakaoOAuth2Client.kt
  src/main/kotlin/com/eatsfinder/global/oauth/client/kakao/dto/KakaoTokenResponse.kt
  src/main/kotlin/com/eatsfinder/global/oauth/client/kakao/dto/KakaoUserAccountResponse.kt
  src/main/kotlin/com/eatsfinder/global/oauth/client/kakao/dto/KakaoUserInfoResponse.kt
  src/main/kotlin/com/eatsfinder/global/oauth/client/kakao/dto/KakaoUserPropertiesResponse.kt
  src/main/kotlin/com/eatsfinder/global/oauth/config/RestClientConfig.kt
  src/main/kotlin/com/eatsfinder/global/oauth/converter/OAuth2ProviderConverter.kt
  src/main/kotlin/com/eatsfinder/global/security/SecurityConfig.kt
  src/main/kotlin/com/eatsfinder/global/security/jwt/JwtAuthenticationFilter.kt
  src/main/kotlin/com/eatsfinder/global/security/jwt/JwtAuthenticationToken.kt
  src/main/kotlin/com/eatsfinder/global/security/jwt/JwtPlugin.kt
  src/main/kotlin/com/eatsfinder/global/security/jwt/UserPrincipal.kt
  src/main/kotlin/com/eatsfinder/global/web/WebConfig.kt
  src/main/resources/application.yml
Labels: ✨ Feat

#8 Feat/comment k
  src/main/kotlin/com/eatsfinder/domain/category/controller/CategoryController.kt
  src/main/kotlin/com/eatsfinder/domain/category/dto/CategoryResponse.kt
  src/main/kotlin/com/eatsfinder/domain/category/repository/CategoryRepository.kt
  src/main/kotlin/com/eatsfinder/domain/category/service/CategoryService.kt
  src/main/kotlin/com/eatsfinder/domain/category/service/CategoryServiceImpl.kt
  src/main/kotlin/com/eatsfinder/domain/comment/controller/CommentController.kt
  src/main/kotlin/com/eatsfinder/domain/comment/dto/CommentRequest.kt
  src/main/kotlin/com/eatsfinder/domain/comment/dto/CommentResponse.kt
  src/main/kotlin/com/eatsfinder/domain/comment/model/Comment.kt
  src/main/kotlin/com/eatsfinder/domain/comment/repository/CommentRepository.kt
  src/main/kotlin/com/eatsfinder/domain/comment/service/CommentService.kt
  src/main/kotlin/com/eatsfinder/domain/comment/service/CommentServiceImpl.kt
  src/main/kotlin/com/eatsfinder/domain/post/repository/PostRepository.kt
Labels: ✨ Feat

#10 Feat/dotenv k
  build.gradle.kts
  src/main/kotlin/com/eatsfinder/EatsFinderApplication.kt
  src/main/resources/application.yml
Labels: ✨ Feat

#12 Feat/jwt k
  src/main/kotlin/com/eatsfinder/domain/user/service/OAuth2LoginService.kt
  src/main/kotlin/com/eatsfinder/global/security/jwt/JwtAuthenticationFilter.kt
  src/main/kotlin/com/eatsfinder/global/security/jwt/JwtPlugin.kt
  src/main/kotlin/com/eatsfinder/global/security/jwt/UserPrincipal.kt
  src/main/resources/application.yml
Labels: ♻️ Refactor

#15 Feat/oauth k
  src/main/kotlin/com/eatsfinder/domain/user/controller/OAuth2LoginController.kt
  src/main/kotlin/com/eatsfinder/global/security/SecurityConfig.kt
Labels: ♻️ Refactor

#17 Feat/dotenv k
  src/main/resources/application.yml
Labels: ♻️ Refactor

#18 Feat/depoly n
  .github/workflows/cicd.yml
  Dockerfile.nestjs
  src/main/nest/main.ts
Labels: 🚀 Deploy, nestjs

#19 feat/depoly n
  package.json
Labels: 🚀 Deploy, nestjs

#20 🚀 Deploy: 도커 컨테이너 이름 변경(#13)
  .github/workflows/cicd.yml
Labels: 🚀 Deploy, nestjs

#21 Feat/dotenv k
  src/main/kotlin/com/eatsfinder/global/oauth/client/google/GoogleOAuth2Client.kt
  src/main/kotlin/com/eatsfinder/global/oauth/client/kakao/KakaoOAuth2Client.kt
  src/main/resources/application.yml
Labels: ♻️ Refactor

#22 Feat/dotenv n
  .env.sample
  package-lock.json
  package.json
  src/main/nest/app/app.controller.spec.ts
  src/main/nest/app/app.controller.ts
  src/main/nest/app/app.module.ts
  src/main/nest/app/app.service.ts
  src/main/nest/main.ts
  src/test/nest/app.e2e-spec.ts
Labels: ✨ Feat, nestjs

#23 🐛 Fix: workflow 수정
  .github/workflows/cicd.yml
Labels: 🐛 Fix, nestjs

#24 Feat/entity n
  .env.sample
  .prettierrc
  package-lock.json
  package.json
  src/main/nest/app/app.module.ts
  src/main/nest/global/prisma/prisma.module.ts
  src/main/nest/global/prisma/prisma.service.ts
  src/main/nest/global/prisma/schema.prisma
  src/main/nest/main.ts
Labels: ✨ Feat, nestjs

#25 Feat/swagger n
  package-lock.json
  package.json
  src/main/nest/global/swagger/swagger.config.ts
  src/main/nest/main.ts
Labels: ✨ Feat, nestjs

#27 ✨ Feat: 도커파일에 Prisma 스크립트 적용(#26)
  Dockerfile.nestjs
Labels: ✨ Feat, nestjs

#28 🐛 Fix: 도커파일 수정(#26)
  Dockerfile.nestjs
Labels: 🐛 Fix, nestjs
