Repository All-eatery/EatsFinder-BE, pull requests merged in 2025-06, with the labels that each got.

#132 Feat/keyword
  build.gradle.kts
  src/main/kotlin/com/eatsfinder/domain/search/controller/SearchController.kt
  src/main/kotlin/com/eatsfinder/domain/search/dto/SearchResponse.kt
  src/main/kotlin/com/eatsfinder/domain/search/model/KeywordLog.kt
  src/main/kotlin/com/eatsfinder/domain/search/repository/KeywordRepository.kt
  src/main/kotlin/com/eatsfinder/domain/search/service/SearchService.kt
  src/main/kotlin/com/eatsfinder/domain/search/service/SearchServiceImpl.kt
  src/main/kotlin/com/eatsfinder/global/pagination/PaginationItemsResponse.kt
  src/main/kotlin/com/eatsfinder/global/redis/JacksonConfig.kt
  src/main/kotlin/com/eatsfinder/global/redis/RedisConfig.kt
  src/main/kotlin/com/eatsfinder/global/security/SecurityConfig.kt
  src/main/resources/application.yml
Labels: ✨ Feat, 🍱 Add, 🐛 Fix, kotlin

#133 ✨ Feat: 전체보기 및 검색(#116)
  src/main/nest/domain/bookmark/controller/bookmark.controller.ts
  src/main/nest/domain/bookmark/service/bookmark.service.ts
  src/main/nest/global/dto/request/find-all-bookmark-place-request.dto.ts
Labels: ✨ Feat, nestjs

#135 Feat/place info detail
  src/main/nest/domain/place/controller/place.controller.ts
  src/main/nest/domain/place/service/place.service.ts
  src/main/nest/global/dto/index.ts
  src/main/nest/global/dto/request/place-post-query.dto.ts
  src/main/nest/global/dto/response/place-detail-response.dto.ts
Labels: ✨ Feat, 🍱 Add, nestjs

#137 Feat/place info
  src/main/kotlin/com/eatsfinder/domain/place/controller/PlaceInfoController.kt
  src/main/kotlin/com/eatsfinder/domain/post/dto/TopPostResponse.kt
  src/main/kotlin/com/eatsfinder/domain/post/repository/PostRepositoryImpl.kt
  src/main/kotlin/com/eatsfinder/global/security/SecurityConfig.kt
Labels: ♻️ Refactor, 🐛 Fix, kotlin

#138 Feat/place info detail
  src/main/nest/domain/place/service/place.service.ts
  src/main/nest/global/dto/response/place-detail-response.dto.ts
Labels: ✨ Feat, nestjs
